export { BrowserFrame } from "./BrowserFrame";
export { HeroSection } from "./HeroSection";
export { FeatureSection } from "./FeatureSection";
export { Navbar } from "./Navbar";
export { CTASection } from "./CTASection";
export { Footer } from "./Footer";
export { default as SplineWrapper } from "./SplineWrapper";
export { ProblemSolution } from "./ProblemSolution";
export { HowItWorks } from "./HowItWorks";
export { Testimonials } from "./Testimonials";
export { PricingSection } from "./PricingSection";
